[build]
  publish = "public"
  functions = "src/functions"

[dev]
  publish = "public"
  functions = "src/functions"

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/skills"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200
